### ISSUE TITLE
stream.on error

### ISSUE THREAD

**Issue by Mefistophell** [jaydenseric/apollo-upload-examples#10]
Hello! 
I just want to understand: does it make any sense?

The first error handler - 
https://github.com/jaydenseric/apollo-upload-examples/blob/master/api/resolvers.mjs#L23
The second one - 
https://github.com/jaydenseric/apollo-upload-examples/blob/master/api/resolvers.mjs#L30
in the same event.

**Comment by jaydenseric** [comment]
The first one listens for errors to do with the upload stream from the client, the second listens for errors to do with writing the file.

Node.js streams are not very intuitive 😅

**Comment by Mefistophell** [comment]
I see! 
Thank you very much for your answer :)
