### ISSUE TITLE
File not being passed to server

### ISSUE THREAD

**Issue by edPratt** [jaydenseric/apollo-upload-examples#14]
I'm hoping you can help me see what I am doing wrong here.

On the client the file is being passed to the mutation:
![image](https://user-images.githubusercontent.com/6599975/55813936-a4b1a300-5abb-11e9-8fab-91b26a54e1f4.png)

But then on the server file is undefined:
![image](https://user-images.githubusercontent.com/6599975/55813998-c01cae00-5abb-11e9-986f-b9044f9c2d3a.png)

I think something is wrong with my client side mutation (not sure that's the right way to say that). Please let me know if more information is needed.

**Comment by jaydenseric** [comment]
Is this using a clone of this repo, or as an integration into your own project?

The first step is to see if the client is sending a [valid multipart request](https://github.com/jaydenseric/graphql-multipart-request-spec#multipart-form-field-structure). You can do that using the dev tools network inspector tab, by looking at the request details. If the client is not sending a multipart request, you know the problem is with the Apollo Client links config.

I would guess that your upload HTTP link is not setup correctly?

**Comment by pbassut** [comment]
Ok. I had the same issue and it was because I was using apollo-boost.
The documentation calls out on that, my bad for not paying attention.

Fixing it was a matter of changing:
`import ApolloClient from 'apollo-boost'`
to:
`import { ApolloClient } from 'apollo-client'`

**Comment by jaydenseric** [comment]
Thanks @pbassut, hopefully that was the same issue @edPratt had.

**Comment by edPratt** [comment]
This is for another project, and I am not using apollo-boost. I've verified that I am not sending a multipart request, just application/json. I noticed I missed the step to pass createUploadLink to the ApolloClient so I added that. Still, it's not sending a multipart request. Could it be because I'm using multiple links via ApolloLink.from(someArrayOfLinks) and then passing that to ApolloClient by any chance? @jaydenseric

**Comment by pbassut** [comment]
@edPratt can you post how you're creating your links?

**Comment by edPratt** [comment]
@pbassut  Of course: 
![image](https://user-images.githubusercontent.com/6599975/56382714-0671bb80-61e6-11e9-83f9-4982440a7949.png)

**Comment by pbassut** [comment]
Can you drop everything else and just leave uploadLink?
By the way, I'm not using httpLink. I'm assuming uploadLink already includes it. 
So, I would first remove httpLink and if that doesn't work, drop everything else and try only the uploadLink. That way you would know it's an issue with your link stack(possibly).

**Comment by edPratt** [comment]
@pbassut that solved the issue of sending a multipart request and the file to the server. Thanks so much for your help @pbassut and @jaydenseric. Seems like I need to refactor how I'm putting the links together, but that's a separate issue. Cheers
