### ISSUE TITLE
What does stream.truncated mean?

### ISSUE THREAD

**Issue by mrdulin** [jaydenseric/apollo-upload-examples#22]
https://github.com/jaydenseric/apollo-upload-examples/blob/master/api/resolvers.mjs#L24

I don't find any information about `truncated` property for nodejs `ReadStream` from the documentations of nodejs. Where does it come from?

Thanks for explaining.

**Comment by mike-marcacci** [comment]
I admire the deep dive!! This is a property [set by busboy](https://github.com/mscdex/busboy/blob/db9b25f2b88fd4689d78d74b1fdc9de7f10d5f3d/lib/types/multipart.js#L222) (which `graphql-upload` uses under the hood) when a file exceeds the configured max file size limit.

**Comment by mike-marcacci** [comment]
To be honest, I'm not sure that should even be in the example, though, as the actual stream passed to you is no longer a busboy stream. @jaydenseric do you know if that line is still relevant at all? I assume the behavior should be to delete the partially uploaded file for any error.

**Comment by mrdulin** [comment]
@mike-marcacci Thanks for explaining. I think it should handle internally, don't expose it. Because the user should not know this custom property.

**Comment by mike-marcacci** [comment]
@mrdulin you're correct; this example is out of date; the `truncated` property is _not_ exposed, and instead [an error](https://github.com/jaydenseric/graphql-upload/blob/0288c619bc9c487bc49ce7585629126465d6259c/src/processRequest.mjs#L333) is propagated down the stream.

**Comment by jaydenseric** [comment]
@mike-marcacci I've significantly refreshed the example API and app. Would you like to review how the file stream is processed here, perhaps commenting a few of the gotchas (like, why there are two error event handlers)?

https://github.com/jaydenseric/apollo-upload-examples/blob/fcd1a7f64bddcf4ff42d6a83b4ec88ccb1b71683/api/server.js#L32-L43

Close this issue once you're happy!

**Comment by jaydenseric** [comment]
@mike-marcacci I assume everything was ok with the changes, please reopen if not.
