### ISSUE TITLE
Variable picture got invalid value {}; Expected type Upload. Upload value invalid.

### ISSUE THREAD

**Issue by dewaleolaoye** [jaydenseric/apollo-upload-examples#25]
I'm using `nestjs`  and I want to upload images but I'm getting this error message
```

"message": "Variable \"$picture\" got invalid value {}; Expected type Upload. Upload value invalid.",
```

this is how I passed  my values in postman 
{
  ` operations`: `{"query":"mutation UploadFile($picture: Upload!) {\n  uploadFile(picture: $picture)\n}"}`,
  `map`: `{"0": ["variables.picture"]}`,
  `0`: `The file I want to upload`
}

and this is my code, please what I'm I doing wrong?
![typegraphql](https://user-images.githubusercontent.com/44645460/73195812-cf461880-412e-11ea-9080-1eb8b82d6d78.PNG)

**Comment by jaydenseric** [comment]
Please use tidy [fenced and syntax-highlighted code blocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting) when sharing code in markdown on GitHub, it makes it much easier for people to read correctly, like this:

```json
{
  ` operations`: `{"query":"mutation UploadFile($picture: Upload!) {\n  uploadFile(picture: $picture)\n}"}`,
  `map`: `{"0": ["variables.picture"]}`,
  `0`: `The file I want to upload`
}
```

As can be seen, what you shared as using with postman is is invalid JSON, you can't use backticks around field names and values.

Also, it looks like the `variables` field is missing in the `operations` JSON, you can see an example of what is should look like with the file replaced with `null` here:

https://github.com/jaydenseric/graphql-multipart-request-spec#examples

**Comment by dewaleolaoye** [comment]
Thanks for the correction @jaydenseric I'm getting the same error and I've passed the necessary values, please help

```json
{
   "query": "mutation UploadFile($picture: Upload!) {uploadFile(picture: $picture) }", 
   "variables": {"picture": null}
}
```
and for the `map` field this is what I pass
```json 
{ 
   map:  ["variables.picture"] 
}
```
and then the file field which is `0`
```json 
   0: uploaded_file
```
