### ISSUE TITLE
Unhandled Rejection (Error): Unexpected token M in JSON at position 0

### ISSUE THREAD

**Issue by donniekerr** [jaydenseric/apollo-upload-examples#31]
I'm getting this error Unhandled Rejection (Error): Unexpected token M in JSON at position 0 
any idea why? below is my code and screenshots of the error in console. 
app.js
`const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: createUploadLink({
    uri: "https://onegraph.azurewebsites.net/api/magda",
  }),
});
`
input  component change event
`const onChange = (e) => {
    let f = e.target.files[0];
    let v = { variables: { file: f } };
    uploadFile(v).then(() => {
      apolloClient.resetStore();
    });
  };`
upload file query 
`import gql from "graphql-tag";

export const UPLOADFILE = gql`
  mutation uploadFile($file: Upload!) {
    uploadFile(file: $file) {
      name
      type
      size
      lastModified
    }
  }
`;`
<img width="461" alt="Screen Shot 2020-09-04 at 9 19 26 AM" src="https://user-images.githubusercontent.com/41065378/92249680-1304bb80-ee90-11ea-93af-d46d81589430.png">
<img width="839" alt="Screen Shot 2020-09-04 at 9 21 26 AM" src="https://user-images.githubusercontent.com/41065378/92249682-139d5200-ee90-11ea-854c-87ec48690dff.png">
<img width="365" alt="Screen Shot 2020-09-04 at 9 21 02 AM" src="https://user-images.githubusercontent.com/41065378/92249686-139d5200-ee90-11ea-816b-56ae5ae209d5.png">
<img width="646" alt="Screen Shot 2020-09-04 at 9 20 10 AM" src="https://user-images.githubusercontent.com/41065378/92249687-1435e880-ee90-11ea-832f-52be73aff391.png">

**Comment by jaydenseric** [comment]
That is probably due to the requirements of the `ttps://onegraph.azurewebsites.net/api/magda` API endpoint you are using. They either only accept GET requests, or require some sort of query string parameter in every request.

Chances are these sort of fetch errors will work better soon; there is currently a bug about to be fixed:

https://github.com/jaydenseric/apollo-upload-client/issues/222

**Comment by donniekerr** [comment]
Thank you.  This is my graphQL endpoint and doesn't use any query params.  My server-side is configured exactly as Apollo documents https://www.apollographql.com/docs/apollo-server/data/file-uploads/#gatsby-focus-wrapper and it added the Upload type.  

That said, I read over the Apollo Best Practices and decided to go direct client-side SAS Upload using Azure Blob Storage SDK.  This approach is what they actually recommend.  It is more efficient to go direct, especially since Apollo doesn't support File Uploads without a 3rd party package on the client. Given that, I will close this issue, but I still think there is a issue.

Thank you.
