### ISSUE TITLE
How to delete files by ID?

### ISSUE THREAD

**Issue by maheraldous** [jaydenseric/apollo-upload-examples#35]
Hello @jaydenseric 

How to delete files by ID? or by anything useful in the playground.

Thanks in advance

**Comment by jaydenseric** [comment]
You would create a new `fileDelete` mutation that accepts a `fileId` parameter, and in the resolver you would delete the file from the filesystem where it is stored and the "database" entry for that file ID.

In a real app you would probably have stored the file in the cloud, so the `fileDelete` mutation resolver in that case would await a request to the cloud provider that deletes the file from storage, and if successful, delete the file with that ID from the database. If you are using a image thumbnailing service like [imgix](https://www.imgix.com), you may additionally want to await a request to their API telling it to flush any thumbnails that may have been created for that file.

Hope that helps :)
