### ISSUE TITLE
Unable to upload multiple files

### ISSUE THREAD

**Issue by Safnaj** [jaydenseric/apollo-upload-examples#48]
I have two mutations implemented as singleUpload & multiUpload. singleUpload working fine and unable to upload multiple files using graphQlUploadExpress. Here is my code :

server.js
```
const app = express();
app.use(cors());
app.use(express.json({ limit: "50mb" }));
app.use(graphqlUploadExpress({ maxFileSize: 10000000, maxFiles: 10 }));
```

upload.js
```
import GraphQLUpload from "graphql-upload/GraphQLUpload.mjs";

export default {
  Upload: GraphQLUpload,
  Mutation: {
    singleUpload: async (_, { fileInput: { id, name, file } }) => {
      try {
        const { createReadStream, filename } = await file;
        const stream = createReadStream();

        const params = {
          Bucket: process.env.S3_BUCKET,
          Key: `${id} - ${name}/${filename}`,
          Body: stream,
        };

        const res = await s3.upload(params).promise();
        console.log("File uploaded successfully");
        return `Uploaded Location: ${res.Location}`;
      } catch (error) {
        console.error("Error uploading file:", error);
        throw new Error("Failed to upload file");
      }
    },

    multiUpload: async (_, { fileInput: { id, name, files } }) => {
      try {
        const uploadPromises = files.map(async (file) => {
          const { createReadStream, filename } = await file;
          const stream = createReadStream();

          const params = {
            Bucket: process.env.S3_BUCKET,
            Key: `${id} - ${name}/${filename}`,
            Body: stream,
          };

          await s3.upload(params).promise();
          return `Uploaded: ${filename}`;
        });

        const res = await Promise.all(uploadPromises);
        console.log("File uploaded successfully");
        return `Uploaded Location: ${res.Location};`;
      } catch (error) {
        console.error("Error uploading files:", error);
        throw new Error("Failed to upload files");
      }
    },
  },
```
};

schema.graphql : 

```
scalar Upload

input MultiFileInput {
  id: String!
  name: String!
  files: [Upload!]!
}
```

**Comment by jaydenseric** [comment]
What is the error?

**Comment by Safnaj** [comment]
> What is the error?

When not setting the **multipart/form-data** in apollo-studio getting below error :

`BadRequestError: Invalid object path for the ‘map’ multipart field entry key ‘0’ array index ‘0’ value ‘variables.fileInput.files.0’ (https://github.com/jaydenseric/graphql-multipart-request-spec).`

With header setting : 
`Error: Multipart: Boundary not found`

**Comment by jaydenseric** [comment]
> When not setting the multipart/form-data in apollo-studio

I don't understand what you mean. If you are not sending a multipart request, why would you expect files to upload?

> With header setting :

I don't understand this either; you have a HTTP header in the response called `setting`, with a text content of `Error: Multipart: Boundary not found`?

**Comment by Safnaj** [comment]
> > When not setting the multipart/form-data in apollo-studio
> 
> I don't understand what you mean. If you are not sending a multipart request, why would you expect files to upload?
> 
> > With header setting :
> 
> I don't understand this either; you have a HTTP header in the response called `setting`, with a text content of `Error: Multipart: Boundary not found`?

I meant I tried with & without header.

**Comment by jaydenseric** [comment]
> I meant I tried with & without header.

What header? You are not explaining things enough.

**Comment by Safnaj** [comment]
> multipart/form-data

**Content-Type: multipart/form-data** is the header I set in apollo studio. Is there anything missing in my code implementation ?

**Comment by jaydenseric** [comment]
You're using a commercial tool I didn't build (Apollo Studio), with your personal project code that's not in this repo, so why are you raising an issue here? You can ask Apollo customer support how to use their product Apollo Studio.

In this repo, issues can be raised to maintain the code in these example projects with bug fixes or improvements. I can't support third party tools or project code outside this repository.

**Comment by Safnaj** [comment]
I didn't ask you to debug Apollo Studio. I just explained how am testing it and what is the output am getting. 
Anyway thanks for the time.
