### ISSUE TITLE
Why server get upload.file.stream of undefined

### ISSUE THREAD

**Issue by solayao** [jaydenseric/apollo-upload-examples#5]
client send a graphql like this:
![image](https://user-images.githubusercontent.com/14294893/39528790-a6244948-4e57-11e8-89ad-fc2f7f57f420.png)
and the image msg like this:
![image](https://user-images.githubusercontent.com/14294893/39528867-df3c7e6c-4e57-11e8-9842-6199f73bf1e1.png)
but the server get the file only has a uid props after used 'apollo-upload-server'
![image](https://user-images.githubusercontent.com/14294893/39528986-296363fc-4e58-11e8-82f7-09e63cf28c56.png)
but your demo has got the props(stream, filename, mimetype, encoding) in file prop.

why i cannot get those props in file prop

**Comment by jaydenseric** [comment]
If you use the Chrome inspector network activity tab, is the body of the request a multipart form? If it is not, that would mean that `apollo-upload-client` is not configured properly. If it is, that would mean `apollo-upload-server` is probably not setup correctly.

**Comment by solayao** [comment]
this is the client request, like this
![image](https://user-images.githubusercontent.com/14294893/39529659-c8538a2c-4e59-11e8-8f0a-ee15683f6701.png)
and the server of the graphql setup by this:
```
const { graphqlKoa } = require('apollo-server-koa');
const { apolloUploadKoa } = require('apollo-upload-server');
const bodyparser = require('koa-bodyparser');
const schemas = require('../schemas');
const router = require('koa-router')();

// add url-route:

router
    .post('/graphql', bodyparser(), apolloUploadKoa(), graphqlKoa(ctx => ({
        schema: schemas,
        context: {
            mongo: ctx.mongo,
        },
        tracing: true,
        cacheControl: true,
        formatError: err => {
            if (err.originalError && err.originalError.error_message) {
                err.message = err.originalError.error_message;
            }
            return err;
        },
    })))
```
after all , i think the problem cause by the client side, but i cannot found the reason
Help~~~┑(￣Д ￣)┍

**Comment by jaydenseric** [comment]
It's definitely a problem on the client, because it is not sending a multipart form (upload) to the server. If you are sure the client is setup right, are you sure that the file is an instance of `window.File`?

**Comment by solayao** [comment]
i console the file instanceof File, the result is true
so the problem cause by my configure with reactClient？
And this is my client side configure
```
const client = new ApolloClient({
  uri: `${serverConfig.serverHost}:${serverConfig.serverPort}/graphql`,
  cache: new InMemoryCache(),
});

ReactDOM.render(
  <Router>
    <ApolloProvider client={client}>
      <App />
    </ApolloProvider>
  </Router>,
  document.getElementById('root')
);
```

**Comment by jaydenseric** [comment]
That’s the problem 😅

You need to follow [the setup instructions](https://github.com/jaydenseric/apollo-upload-client#setup), to [construct an `ApolloClient` with the special HTTP link](https://github.com/jaydenseric/apollo-upload-examples/blob/master/app/providers/with-data.js#L18).
