### ISSUE TITLE
stream.on undefined, i write code base on the example of the api/resolver.mjs file

### ISSUE THREAD

**Issue by makbarsyahwana** [jaydenseric/apollo-upload-examples#7]
`Uncaught (in promise) Error: GraphQL error: Cannot read property 'on' of undefined
    at new ApolloError (ApolloError.js:34)
    at Object.next (QueryManager.js:98)
    at SubscriptionObserver.next (zen-observable.js:154)
    at httpLink.js:140`

**Comment by jaydenseric** [comment]
Is that a server, or browser error?

**Comment by makbarsyahwana** [comment]
i'm not sure, but if I query or mutate something on graphql it's work except file uploading, and the server use express anyway

**Comment by jaydenseric** [comment]
I meant, is the error emitted in your browser console or Node.js console (if Node.js, is it the API server or app server?).

**Comment by makbarsyahwana** [comment]
it's browser console

**Comment by jaydenseric** [comment]
You should be using the terminating HTTP link exported from this package, looking at the `at httpLink.js:140` part of the error, it appears the standard HTTP link is being used. Note that you can not use Apollo Boost, you have to setup the client and links yourself.

**Comment by jaydenseric** [comment]
Feel free to discuss further if that did not solve the problem 🙏
