### ISSUE TITLE
not issue feature file already downloaded

### ISSUE THREAD

**Issue by simonjoom** [jaydenseric/apollo-upload-examples#8]
i suggest to add a check to see if the file was already downloaded
I passed some hour to figure out that i need to close the stream else it's not working.

here the code : 

```
const processUpload = async (upload) => {
  const { stream, filename, mimetype, encoding } = await upload;
  const el = existInDB(filename);
  if (el.length > 0) {
    stream.resume();
    stream.on('end', () => {
      console.log('got to the end, but did not read anything');
    });
    var out = el.map(a => Object.assign({}, a))
    return out[0]
  } else {
    const { id, path } = await storeFS({ stream, filename });
    return storeDB({ id, filename, mimetype, encoding, path }); 
  }
}
```

```
export const existInDB = filename => { 
  return _.toArray(db.get("uploads")).filter(function(e) {
    return e.filename === filename;
  });
};

```

**Comment by jaydenseric** [comment]
Thanks for the suggestion, but for the example it is better that multiple files with the same filename are stored as that is what is most useful in real situations. Imagine if two users tried to upload `profile-picture.jpg` when setting their avatars; both should save separately as the ownership, and probably contents, are different.
