### ISSUE TITLE
GraphQL type Upload?

### ISSUE THREAD

**Issue by nzmedet** [jaydenseric/apollo-upload-examples#9]
Where did you get that type? `type Upload` is not defined anywhere 
used in 
```
 type Mutation {
    singleUpload(file: Upload!): File!
    multipleUpload(files: [Upload!]!): [File!]!
  }
```

Reason i'm asking: My server says `path field is empty in type File` when uploading from react web-app, but it works in react-native app

```
type Mutation {
  uploadImage(file: File): Image
}
input File {
  name: String!
  type: String!
  size: Int!
  path: String!
}
type Image {
  filename: String
  width: Int
  height: Int
}
```

**Comment by eniko1556** [comment]
If you are using executable schema, you need to setup Upload scalar.
From the doc: https://www.apollographql.com/docs/guides/file-uploads.html#File-upload-with-schema-param

Here is what you need to do : 

```
const { ApolloServer, makeExecutableSchema, gql, GraphQLUpload } = require('apollo-server');

const typeDefs = gql`
  scalar Upload
  ....
`;

const resolvers = {
  Upload: GraphQLUpload,
  Query: {
   ...
  },
  Mutation: {
  ...
  },
};

const schema = makeExecutableSchema({ typeDefs, resolvers });

const server = new ApolloServer({
  schema,
});

server.listen().then(({ url }) => {
  console.log(`🚀 Server ready at ${url}`);
});
```

**Comment by nzmedet** [comment]
Yes that solved, should have read docs carefully xD

**Comment by jaydenseric** [comment]
[I've updated the examples](https://github.com/jaydenseric/apollo-upload-examples/commit/921aa517baeeb5a967bf02788a8ac49d9407d998), [see here for context](https://github.com/apollographql/apollo-server/issues/1854#issuecomment-433921990). There are step by step migration instructions towards the end of the comment.
